.ALIASES
E_En            En(3=CM 4=INN 1=D 2=0 )
V_VCC           VCC(+=VCC -=0 )
V_VEE           VEE(+=0 -=VEE )
V_VCM           VCM(+=CM -=0 )
V_Vd            Vd(+=D -=0 )
X_U1            U1(+=INP -=INN V+=VCC V-=VEE OUT=OUT )
E_Ep            Ep(3=INP 4=CM 1=D 2=0 )
_    _(INN=INN)
_    _(d=D)
_    _(VEE=VEE)
_    _(CM=CM)
_    _(INP=INP)
_    _(VCC=VCC)
_    _(OUT=OUT)
.ENDALIASES
