.ALIASES
V_V9            V9(+=N33084 -=0 ) CN @CHAPTER 4.IV(sch_1):I32550@SOURCE.VDC.Normal(chips)
M_M11           M11(d=N32415 g=N33644 s=0 s=0 ) CN @CHAPTER 4.IV(sch_1):I67497@ANAS.NFET1.Normal(chips)
M_M9            M9(d=N32415 g=N33084 s=0 s=0 ) CN @CHAPTER 4.IV(sch_1):I65330@ANAS.NFET1.Normal(chips)
V_V10           V10(+=N33430 -=0 ) CN @CHAPTER 4.IV(sch_1):I32587@SOURCE.VDC.Normal(chips)
V_V8            V8(+=N32415 -=0 ) CN @CHAPTER 4.IV(sch_1):I32351@SOURCE.VDC.Normal(chips)
M_M10           M10(d=N32415 g=N33430 s=0 s=0 ) CN @CHAPTER 4.IV(sch_1):I65628@ANAS.NFET1.Normal(chips)
V_V11           V11(+=N33644 -=0 ) CN @CHAPTER 4.IV(sch_1):I32615@SOURCE.VDC.Normal(chips)
.ENDALIASES
